#!/bin/zsh
set -eux -o pipefail

# https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-getting-started-enable-ssh-connections.html

if ! session-manager-plugin; then
    curl --fail \
        'https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb' \
        -o /tmp/session-manager-plugin.deb
    sudo apt-get install /tmp/session-manager-plugin.deb
    session-manager-plugin
    rm /tmp/session-manager-plugin.deb
fi
