#!/bin/zsh
set -eux -o pipefail

if [[ $(lsb_release --release --short) != '20.04' ]]; then
    echo 'setup script targets an ubuntu 20.04, instead this is' $(lsb_release --release --short)
    exit 1
fi

if which virtualbox; then
    echo 'virtualbox already installed'
    exit 0
fi

echo 'check script again, not sure its good'
echo 'especially it install many recommends, old linux kernels and stuff, all not very clean to use/do'
echo 'when doing the next time, pay close attention to what it will install, maybe try with aptitude'
exit 1

# see https://www.virtualbox.org/wiki/Linux_Downloads for newer versions
# this one is for 19.10 and 20.04
# TODO could probably make a 'curl ls' and find most recent, folder is viewable
wget 'https://download.virtualbox.org/virtualbox/6.1.22/virtualbox-6.1_6.1.22-144080~Ubuntu~eoan_amd64.deb' -O /tmp/vbox.deb

# note that this does not seem to install apt repositories, updates will not happen
sudo apt-get install --no-install-recommends /tmp/vbox.deb
# TODO ok weird, the output of apt-get told me that it is using virtualbxo-6.1 instead, so not actually using my download?
# is that good enough anyway? but then trying that package it tells me not possible?! I dont understand
rm /tmp/vbox.deb
