#!/bin/zsh
set -eux -o pipefail

if [[ $(lsb_release --release --short) != '20.04' ]]; then
    echo 'setup script targets an ubuntu 20.04, instead this is' $(lsb_release --release --short)
    exit 1
fi

if which virtualbox; then
    echo 'virtualbox already installed'
    exit 0
fi

# see https://www.virtualbox.org/wiki/Linux_Downloads for newer versions
# this one is for 19.10 and 20.04
wget 'https://download.virtualbox.org/virtualbox/6.1.16/virtualbox-6.1_6.1.16-140961~Ubuntu~eoan_amd64.deb' -O /tmp/vbox.deb

# note that this does not seem to install apt repositories, updates will not happen
sudo apt-get install /tmp/vbox.deb
rm /tmp/vbox.deb
