#!/bin/zsh
set -eu -o pipefail

base=${0:a:h}
cd $base

mkdir seed

cp seed-run seed/run

hostname > seed/hostname

mkdir seed/ssh
cp ~/.ssh/id_rsa ~/.ssh/id_rsa.pub seed/ssh
cp ~/.ssh/ptc_git_id_rsa ~/.ssh/ptc_git_id_rsa.pub seed/ssh

cp ~/.ssh/known_hosts2 seed/ssh/known_hosts2
