#!/bin/zsh
set -eux -o pipefail

# make sure bluetooth is powered off by default on startup
# (we dont stop the service, just power off the hardware, if any)

function adapt {
    awk '
    /^AutoEnable=false$/ {$0="AutoEnable=true"; found=1}
    /^AutoEnable=true$/ {found=1}
    {print}
    END { if (!found) {print "AutoEnable=true"} }
    ' /etc/bluetooth/main.conf
}

if adapt | diff - /etc/bluetooth/main.conf; then
    echo 'no change needed'
else
    adapt | sponge | sudo tee /etc/bluetooth/main.conf
fi
