#!/bin/zsh
set -eux -o pipefail

# make sure bluetooth is powered off by default on startup
# (we dont stop the service, just power off the hardware, if any)

if [[ ! -f /etc/bluetooth/main.conf ]]; then
    exit
fi

function adapt {
    awk '
    /^AutoEnable=true$/ {$0="AutoEnable=false"; found=1}
    /^AutoEnable=false$/ {found=1}
    {print}
    END { if (!found) {print "AutoEnable=false"} }
    ' /etc/bluetooth/main.conf
}

if adapt | diff - /etc/bluetooth/main.conf; then
    echo 'no change needed'
else
    adapt | sudo sponge /etc/bluetooth/main.conf
fi
