
#export LC_ALL=en_US.UTF-8
#export LC_CTYPE=en_US.UTF-8
#export LANG=en_US.UTF-8

source ~/config/dots/zshrc.d/antigen.zsh
source ~/config/dots/zshrc.d/path.zsh
source ~/config/dots/zshrc.d/basics.zsh
source ~/config/dots/zshrc.d/fzf.zsh
source ~/config/dots/zshrc.d/shortcuts.zsh
