#!/bin/zsh
set -eux -o pipefail

# install nodejs
# see https://nodejs.org/en/

# see https://nodejs.org/en/download/ for latest LTS version
version='v18.13.0'
# NOTE the .xz versions are smaller than .gz because of better compression
url='https://nodejs.org/dist/'$version'/node-'$version'-linux-x64.tar.xz'

prefix=$HOME/bin/nodejs

function install {
    mkdir -p $prefix
    # see https://install-node.vercel.app/ at the very end
    # installation is just extraction, not sure if that's always okay when
    # installing over an older version, this way previous installed
    # packages will stay (npm install -g ...)
    # not sure if npm itself gets updated here
    curl -sfLS $url | tar --extract --xz --file=- --strip-components=1 --directory=$prefix
}

if [[ ! -e $prefix || ! -e $prefix/bin/node || ! -e $prefix/bin/npm ]]; then
    install
fi

[[ $(which node) == $prefix/bin/node ]]
[[ $(which npm) == $prefix/bin/npm ]]

if [[ $(node --version) != $version ]]; then
    install
fi

# NOTE
# 'npm install --global' goes to the install prefix
# otherwise local folder
# see https://nodejs.org/en/blog/npm/npm-1-0-global-vs-local-installation/#two-paths
