#!/bin/zsh
set -eux -o pipefail

cd ${0:a:h}/tmux

sudo apt-get -yqq install git autoconf automake pkg-config libevent-dev libncurses5-dev byacc

sh autogen.sh
./configure
make -j$(nproc)
sudo make install
