#!/bin/zsh
set -eux -o pipefail

h=${0:a:h}

# config file
ln -sfT $h/tmux.conf ~/.tmux.conf

( # prepare pipenv for tmux status line python code
    cd $h/python
    sudo apt-get -qq install -y python3.7-dev # psutil needs python3.7-dev
    pipenv install
)

( # tmux from git
    cd $h/tmux

    sudo apt-get -yqq install git autoconf automake pkg-config libevent1-dev libncurses5-dev byacc

    sh autogen.sh
    ./configure
    make -j$(nproc)
    sudo make install
)
