#!/bin/zsh
set -eux -o pipefail

# maybe see https://www.spotify.com/ch-de/download/linux/
sudo snap install spotify

# TODO can we control the settings, like high quality, show unavalaible, hide feed, ...?
# might be possible at ~/snap/spotify/current/.config/spotify
