#!/bin/zsh
set -eux -o pipefail

# NOTE 'sudo snap install vlc' provides usually a newer version
# but snaps just dont work so nicely sometimes, slow startup and maybe other things
# the apt version is new enough
# on https://wiki.videolan.org/Documentation:Installing_VLC/
# there is a repository but it doesnt seem updated and/or secure

sudo apt-get install -qy vlc

# NOTE we start vlc with the --config option to use our config
# symlinking a config doesnt work, because vlc replaces the symlink
# snap config by default was in ~/snap/vlc/common/vlcrc
