#!/bin/zsh
set -eux -o pipefail

sudo snap install vlc

# TODO we start vlc with the --config option, symlinking doesnt work, vlc replaces the symlink
# config by default is in ~/snap/vlc/common/vlcrc
