#!/bin/zsh
set -eux -o pipefail

# try to find out if there is a manual installation active
# NOTE not doing it automatically, I didnt test if it works without reboot or anything
if which nvidia-uninstall; then
    echo 'There seems to be a manual nvidia driver installation.' 2>&1
    echo 'Try "sudo nvidia-uninstall" first.' 2>&1
    echo 'Probably best outside X, and then restart and see if all is clean.' 2>&1
    exit 1
fi

# simple check to see if there is an nvidia gpu, might not be perfect
# TODO this failed for A100 instances
# TODO 'ubuntu-drivers devices' could also be useful to check instead
if ! lspci | grep -e 'VGA.*NVIDIA' -e Tesla; then
    echo 'no nvidia gpu found'
    exit 0
fi

# use
# > ubuntu-drivers list
# to see what are the available options
# to switch to a newer version eventually

sudo apt-get install -yqq ubuntu-drivers-common

# check what is the newest recommended version for nvidia
latest=$(ubuntu-drivers list | awk '/^nvidia-driver-[0-9]+,/ {print substr($1, 0, length($1)-1)}' | sort | tail -n 1)
expected=nvidia-driver-495

if [[ $latest != $expected ]]; then
    echo "expected $expected but found $latest"
    exit 1
fi

sudo apt install -yqq $expected

# alternatives
# - see ./manual
# - https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa , maybe the same as ubuntu's own?
# - sudo ubuntu-drivers install [--gpgpu] for server headless?
