#!/bin/zsh
set -eux -o pipefail

# NOTE a previous manual nvidia driver installation doesnt work well with packaged drivers
if which nvidia-uninstall; then
    echo 'There seems to be a manual nvidia driver installation.' 2>&1
    echo 'Try "sudo nvidia-uninstall" first.' 2>&1
    echo 'Probably best outside X, and then restart and see if all is clean.' 2>&1
    exit 1
fi

sudo apt-get install -qqy ubuntu-drivers-common
latest=$(ubuntu-drivers list | awk '/^nvidia-driver-[0-9]+,/ {print substr($1, 0, length($1)-1)}' | sort | tail -n 1)

# NOTE use 'ubuntu-drivers list'
# to see what are the available options
# to switch to a newer version eventually
expected=nvidia-driver-535

if [[ $latest == '' ]]; then
    echo 'No nvidia device found.'
    exit 0
fi

if [[ $latest != $expected ]]; then
    echo "Expected $expected but found $latest." 1>&2
    exit 1
fi

sudo apt install -qqy $expected
# NOTE 'nvidia-smi' wont work before a restart

# NOTE alternatives
# - see ./manual
# - https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa , same as ubuntu's own?
# - sudo ubuntu-drivers install [--gpgpu] for server headless?
