#!/bin/zsh
set -eux -o pipefail

# simple check to see if there is an nvidia gpu, might not be perfect
if ! grep 'VGA.*NVIDIA'; then
    echo 'no nvidia gpu found'
    exit 0
fi

# use
# > ubuntu-drivers list
# to see what are the available options
# to switch to a newer version eventually

# check what is the newest recommended version for nvidia
latest=$(ubuntu-drivers list | awk '/^nvidia-driver-[0-9]+,/ {print substr($1, 0, length($1)-1)}' | sort | tail -n 1)
expected=nvidia-driver-450
[[ $latest == $expected]] || exit 1

sudo apt install $expected

# alternatively get it from nvidia directly, something like
# > wget 'https://us.download.nvidia.com/XFree86/Linux-x86_64/410.78/NVIDIA-Linux-x86_64-410.78.run' -O nvidia.run
# > sudo apt-get -yqq install dkms
# > sudo sh nvidia.run -a -q -n -s --dkms
