#!/bin/zsh
set -eux -o pipefail

if ! which rustup; then
    # from https://www.rust-lang.org/tools/install
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
fi

rustup update
