#!/bin/zsh
set -eux -o pipefail

# problems:
#
# snap would be easiest, but last time snap didnt work well with other components for me
# maybe it also loaded super slowly? maybe just my impression
#
# trying deb package now, it seems to add sources so later apt will update
# (seems to, but I couldnt find that added list in the deb file listing)
# problem is how to get the newest from the slack download page?
# https://slack.com/intl/en-ch/downloads/instructions/ubuntu
# since the actual link might change, it includes the version

wget \
    'https://downloads.slack-edge.com/linux_releases/slack-desktop-4.8.0-amd64.deb' \
    -O /tmp/slack-desktop.deb
sudo apt-get install /tmp/slack-desktop.deb
rm /tmp/slack-desktop.deb
