#!/bin/zsh
set -eux -o pipefail

cd ${0:a:h}

# see that we also checked out all submodules
if (git submodule | grep '^-'); then
    echo 'Some submodules are not checked out.' >&2
    exit 1
fi

../zsh/setup
source ../zsh/path.zsh

# do this early so we dont get LC_* warnings and slow regeneration
../locales/setup
# TODO or just source zshrc or something? split op zshrc in things that I want to reuse here?
export LC_ALL=en_US.UTF-8
# export LANG=en_US.UTF-8
# export LC_ALL=

export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_MODE=a

sudo apt-get update
sudo apt-get upgrade -qy

# switch to hwe kernels (rolling updates)
# see https://wiki.ubuntu.com/Kernel/LTSEnablementStack
# linux-generic is fixed stable kernel, linux-generic-hwe-* is rolling kernel, *-edge is preview rolling kernel
sudo apt-get install -qy --install-recommends linux-generic-hwe-$(lsb_release --short --release)
sudo apt-get remove -y linux-generic
sudo apt-get autoremove -y

# NOTE
# maybe think about if I want to keep the --install-recommends everywhere? installs more than needed usually
# for most okay, but vbox install kernels, that makes updates slow, really needed? I only need one, or two, kernels
# also docker seems to have some kernel install from recommends or suggests or so
# aptitude also seems a bit cleaner than apt-get? remove for example does autoremove in one go if necessary

sudo timedatectl set-timezone Europe/Zurich

# apt installs (sorted)
i=(
    #dtrx # easy and clean archive extraction  # todo gone?
    #git-filter-repo # https://github.com/newren/git-filter-repo/blob/main/INSTALL.md should be there with ubuntu 22.04
    #lm-sensors # check hardware temperatures
    apt-file # apt-file list [package] to see before you install (instead of manually apt-get download [package]; dpgk --contents [file])
    aptitude # 'aptitude why package' is quite cool, there might be more
    attr # set extended file attributes, like 'attr -s com.dropbox.ignored -V 1 .venv'
    bmon # bandwidth monitor
    cmake
    dkms
    g++
    gcp # like cp, but with progress bar among other features
    git
    gocryptfs
    htop
    jq # json query engine
    libboost-dev
    lnav # log file viewer
    markdown # for my ptc notes standup.markdown
    mlocate # quickly find files in the full system
    moreutils # sponge
    mosh # ssh robust for unstable connections
    openssh-server
    partitionmanager # now also shows some of LVM
    pv # monitor data progress thru a pipe
    sshfs
    suckless-tools
    sysstat
    tree
    unzip
    zip
)
sudo apt-get install -qqy $i

# ordered list of custom setups
setups=(
    ssh
    git
    fzf
    top
    htop
    locales
    python
    pdocs
    ptags
    ltstatus
    tmux
    nodejs
    vim
    rust
    osh
    aws
    docker
    kvm
    nodejs
    nvidia
)
for i in $setups; do
    ../$i/setup
done

# NOTE usually a restart is needed at the end to boot into new kernels and modules
