#!/bin/bash
set -eux -o pipefail

$(dirname $0)/../zsh/setup

# switch to zsh
if [ -z ${ZSH_VERSION+1} ]; then
    exec zsh $0
fi

cd ${0:a:h}

# see that we also checked out all submodules
if (git submodule | grep '^-'); then
    echo 'Some submodules are not checked out.' >&2
    exit 1
fi

# pip3 needs this, after setup it's in the zsh config
export PATH=$HOME/.local/bin:$PATH

# do this early so we dont get LC_* warnings and slow regeneration
../locales/setup
export LANG=en_US.UTF-8
export LC_ALL=

# switch to HWE for ubuntu 20.04
# https://wiki.ubuntu.com/Kernel/LTSEnablementStack
sudo apt-get update
sudo apt-get upgrade -qqy
# todo install and autoremove have some interactive popups that ask keep local or update (local seems ok)
# (at least on ec2 ubuntu that happens), could make more unattended?
sudo apt-get install -qqy --install-recommends linux-generic-hwe-20.04
sudo apt-get remove -y linux-generic
sudo apt-get autoremove -y

# NOTE
# maybe think about if I want to keep the --install-recommends everywhere? installs more than needed usually
# for most okay, but vbox install kernels, that makes updates slow, really needed? I only need one, or two, kernels
# also docker seems to have some kernel install from recommends or suggests or so
# aptitude also seems a bit cleaner than apt-get? remove for example does autoremove in one go if necessary

sudo timedatectl set-timezone Europe/Berlin

# apt installs (sorted)
i=()
#i+=dtrx # easy and clean archive extraction  # todo gone?
#i+=lm-sensors # check hardware temperatures
i+=apt-file # apt-file list [package] to see before you install (instead of manually apt-get download [package]; dpgk --contents [file])
i+=aptitude # 'aptitude why package' is quite cool, there might be more
i+=bmon # bandwidth monitor
i+=cmake
i+=dkms
i+=g++
i+=gcp # like cp, but with progress bar among other features
i+=git
i+=gocryptfs
i+=htop
i+=jq # json query engine
i+=libboost-dev
i+=lnav # log file viewer
i+=markdown # for my ptc notes standup.markdown
i+=mlocate # quickly find files in the full system
i+=moreutils # sponge
i+=mosh # ssh robust for unstable connections
i+=openssh-server
i+=pv # monitor data progress thru a pipe
i+=sshfs
i+=suckless-tools
i+=sysstat
i+=tree
i+=unzip
i+=zip
sudo apt-get install -qqy $i

# ordered list of custom setups
setups=(
    ssh
    git
    fzf
    top
    htop
    python
    pdocs
    ptags
    ltstatus
    tmux
    nodejs
    vim
    rust
)
for i in $setups; do
    ../$i/setup
done

# TODO maybe a restart is needed for everything to be ready
