#!/bin/zsh
set -eux -o pipefail

base=${0:a:h}

i=(
    zsh # technically, but of course it's already installed
    zsh-doc # gnu info and html formats? maybe not needed
    git # git info in prompt
)
sudo apt-get install -qy $i

# todo doesn't seem to take effect in the current session (tmux session?)
sudo chsh -s $(which zsh) $(whoami)

ln -sfT $base/zshrc ~/.zshrc
ln -sfT $base ~/.zshrc.d
