#!/bin/bash
set -eux -o pipefail

# switch to zsh
if [ -z ${ZSH_VERSION+1} ]; then
    which zsh || sudo apt-get install -qqy zsh
    exec zsh $0
fi

base=${0:a:h}

i=(
    zsh-doc # gnu info and html formats? maybe not needed
    git # git info in prompt
)
sudo apt-get install -qqy $i

# todo doesn't seem to take effect in the current session (tmux session?)
sudo chsh -s $(which zsh) $(whoami)

ln -sfT $base/zshrc ~/.zshrc
ln -sfT $base ~/.zshrc.d
