source ~/.zshrc.d/antigen.zsh
source ~/.zshrc.d/path.zsh
source ~/.zshrc.d/prompt.zsh
source ~/.zshrc.d/basics.zsh
source ~/.zshrc.d/fzf.zsh
source ~/.zshrc.d/shortcuts.zsh
source ~/.zshrc.d/experimental.zsh
