
# todo get clarity on this
#export LC_ALL=en_US.UTF-8
#export LC_CTYPE=en_US.UTF-8
#export LANG=en_US.UTF-8

base=~/config/i/zsh
source $base/antigen.zsh
source $base/path.zsh
source $base/basics.zsh
source $base/fzf.zsh
source $base/shortcuts.zsh
source $base/experimental.zsh
