
# NOTE zshenv vs zshrc
# zshenv also applies in non-interactive
# if you set, eg, paths there, scripts can use them
# sofar didnt have a use-case yet

# NOTE zcompile could help with slow stuff, last time I tried no big difference

alias src='source'
# alias src='source ~/.zshrc.d/timed-source.zsh'
# 'time zsh -dfic true' should use no startup files
# but this is 1ms, and when I manually return first line in zshrc it's 17ms

src ~/.zshrc.d/preferred-paths.zsh

# NOTE omz deactivated and trying to replace, but not feature parity yet
if false; then
    # NOTE compare manual vs omz
    # use diff on 'setopts'
    # use diff on 'zstyle'
    # and potentially other stuff, env?
    src ~/.zshrc.d/omz.zsh
else
    src ~/.zshrc.d/omz-misc.zsh
    src ~/.zshrc.d/completion.zsh
    # TODO seems super simple, omz needed for that? and the next one as well?
    # src ~/.zshrc.d/plugins/omz/plugins/command-not-found/command-not-found.plugin.zsh
    src ~/.zshrc.d/command-not-found.zsh
    # TODO not sure if it was doing anything? just glue to the actual thing, and is that one even installed?
    # pretty cool https://github.com/mbrubeck/compleat , use for xpman? and others?
    # indeed not installed, not doing anything right now, not sure if needed
    # but seems like an easy one to try for xpman maybe? unless cli has an exporter for zsh comp
    # src ~/.zshrc.d/plugins/omz/plugins/compleat/compleat.plugin.zsh
fi

src ~/.zshrc.d/path.zsh
src ~/.zshrc.d/prompt.zsh
src ~/.zshrc.d/basics.zsh
# TODO this one wraps around the completion system, not so nice, should integrate instead
src ~/.zshrc.d/fzf.zsh
src ~/.zshrc.d/shortcuts.zsh
src ~/.zshrc.d/experimental.zsh
src ~/.zshrc.d/syntax.zsh  # NOTE needs to be sourced last

unalias src

if [[ -v _source_total ]]; then
    printf "%5.1fms in total\n" $_source_total
    unset _source_total
fi
