#!/bin/zsh
set -eux -o pipefail

apts=(
    okular
    breeze-icon-theme  # okular needs it but doesnt have it as a dependency as of 2020-12-23
)
sudo apt-get -yqq install $apts

ln -sfT \
    ~/config/i/okular/okularpartrc \
    ~/.config/okularpartrc

# note there is another config file "okularrc" but that seems more local so I don't persist it
