#!/bin/zsh
set -eux -o pipefail

# TODO I'm not sure if
# > apt install locales
# is the default in ubuntu?
# or do I need to do it?

# NOTES
# > sudo dpkg-reconfigure locales
# to reconfigure with an interactive interface
# selecting all is an option, but makes regeneration slow
# can be annoying after some apt action when it regenerates

sudo ln -sfT ~/config/i/locales/locale.gen /etc/locale.gen
# see also https://help.ubuntu.com/community/Locale
sudo ln -sfT ~/config/i/locales/default-locale /etc/default/locale

sudo locale-gen
