#!/bin/zsh
set -eux -o pipefail

curl -sS https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
sudo apt update
sudo apt install -yqq google-chrome-stable

apts=()
apts+=jq # parse json to change preferences
apts+=moreutils # for sponge
sudo apt-get -yqq install $apts

(
    f=~/.config/google-chrome/Default/Preferences
    if [[ ! -f $f ]]; then
        # need to start chrome first and then exit so that setting are written
        google-chrome
    fi
    # system border works better with tiling window managers
    jq '.browser.custom_chrome_frame=false' $f | sponge $f
)
