#!/bin/zsh
set -eux -o pipefail

# commandline helper (aliased to dbox)
if [[ ! -e ~/bin/dropbox.py ]]; then
    mkdir -p ~/bin
    wget 'https://www.dropbox.com/download?dl=packages/dropbox.py' -O ~/bin/dropbox.py
    chmod +x ~/bin/dropbox.py
else
    echo 'note: we dont redownload dropbox.py'
fi

if [[ ! -e ~/.dropbox-dist ]]; then
    (
        cd ~
        wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
        # it seems like the ~/.dropbox-dist will get updates itself
    )
fi

if pgrep dropbox; then
    echo 'seems like there is already a dropbox running'
else
    ~/.dropbox-dist/dropboxd
    # note: first time this will require you to login
    #   headless -> link is printed
    #   headfull -> browser opens
    #   alternatively, systemctl status dropbox@$USER shows the link when run as service
fi

ln -sfT ~/Dropbox ~/dbox

# install in systemd
# todo security risk to link files here?
sudo ln -sfT \
    ~/config/dots/dropbox.d/dropbox@.service \
    /etc/systemd/system/dropbox@.service
sudo systemctl enable dropbox@$USER
sudo systemctl start dropbox@$USER
