#!/bin/zsh
set -eux -o pipefail

i=()
i+=pulseaudio-utils # for volume in dwm status top right
i+=xinit # start x with .xsession
i+=numlockx # set numlock in .xsession
sudo apt-get -qq install -y $i

if [[ ! -d ~/dwm ]]; then
    git -c core.sshCommand='ssh -i ~/.ssh/private-id-rsa' clone git@bitbucket.org:dkuettel/dwm.git ~/dwm
    cd ~/dwm
    ./setup-requirements.sh
    ./setup-git.sh
    ./install.sh
fi

# note:
# startx calls .xinitrc and if it doesn't exist
# then it uses system defaults in /etc/X11/Xinit
# and /etc/X11/Xsession and then starts
# ~/.xsession which results in a cleaner setup (eg, dbus)
if [[ -e ~/.xinitrc ]]; then
    echo 'should not have an ~/.xinitrc, because then .xsession will not be used'
    false
fi
# todo make it hard directly
t=~/config/dots/dwm; l=~/.xsession
if [[ ! ( $t -ef $l ) ]]; then
    ln -sfT --backup=numbered $t $l
fi

( # cursor themes for X
    sudo apt-get -yqq install oxygen-cursor-theme oxygen-cursor-theme-extra
    mkdir -p ~/.icons
    ln -sfT /usr/share/icons/oxy-blue/ ~/.icons/default
)

if [[ ! -d ~/dmenu ]]; then
    git -c core.sshCommand='ssh -i ~/.ssh/private-id-rsa' clone git@bitbucket.org:dkuettel/dmenu.git ~/dmenu
    cd ~/dmenu
    ./setup-git.sh
    ./install.sh
fi

# slock
if [[ ! -d ~/slock ]]; then
    git clone https://git.suckless.org/slock ~/slock
    cd ~/slock
    sudo apt-get -yqq install libx11-dev make gcc libxft-dev libxinerama-dev libxrandr-dev
    make clean
    make
    sudo make install
fi

# st
if [[ ! -d ~/st ]]; then
    git -c core.sshCommand='ssh -i ~/.ssh/private-id-rsa' clone git@bitbucket.org:dkuettel/st.git ~/st
    cd ~/st
    ./setup-requirements.sh
    ./setup-git.sh
    ./install.sh
fi
