#!/bin/zsh
set -eux -o pipefail

# use
# > ubuntu-drivers list
# to see what are the available options
# to switch to a newer version eventually
sudo apt install nvidia-driver-440

# alternatively get it from nvidia directly, something like
# > wget 'https://us.download.nvidia.com/XFree86/Linux-x86_64/410.78/NVIDIA-Linux-x86_64-410.78.run' -O nvidia.run
# > sudo apt-get -yqq install dkms
# > sudo sh nvidia.run -a -q -n -s --dkms
