#!/bin/zsh
set -eux -o pipefail

# config files
mkdir -p ~/.config/nvim
ln -sfT ~/config/dots/vim/vimrc ~/.config/nvim/init.vim
ln -sfT ~/config/dots/vim/syntax ~/.config/nvim/syntax
ln -sfT ~/config/dots/vim/ftdetect ~/.config/nvim/ftdetect

# dependencies for vim plugins
pip3 install black pynvim

( # nvim from git

    [[ -e ~/neovim ]] || git clone https://github.com/neovim/neovim.git ~/neovim

    if [[ ! -e /usr/local/bin/nvim ]]; then
        sudo apt-get install -yqq ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip
        cd ~/neovim
        # maybe to start fresh: make distclean
        make CMAKE_BUILD_TYPE=Release
        # todo any list of features like in vim?
        sudo make install
    fi
)

# todo :PlugInstall needs to happen, I thought its automatic on first start?
