#!/bin/zsh
set -eux -o pipefail

# config files
mkdir -p ~/.config/nvim
ln -sfT ~/config/dots/vim/vimrc ~/.config/nvim/init.vim

# dependencies for vim plugins
pip3 install black

( # nvim from git

    sudo apt-get install -yqq ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip

    [[ -e ~/neovim ]] || git clone https://github.com/neovim/neovim.git ~/neovim

    if [[ ! -e /usr/local/bin/nvim ]]; then
        # maybe to start fresh: make distclean
        make CMAKE_BUILD_TYPE=Release
        # todo any list of features like in vim?
        sudo make install
    fi
)
