#!/bin/zsh
set -eux -o pipefail

# todo
# cant find out how to do it automatically
# and also how to have it update later
# there seems to be no apt repository?
# https://slack.com/intl/en-ch/downloads/instructions/ubuntu
# the snap version might be good for that, but it didn't work very well for me with login&co

echo 'https://slack.com/intl/en-ch/downloads/instructions/ubuntu'
