#!/bin/zsh
set -eux -o pipefail

# todo
# do we need to check if it's installed?
# it's probably idempotent
# plus xdg-open didn't work when signing in?
# maybe snap doesnt properly register?
# it worked when I copied the link and used xdg-open on the terminal

if [[ ! -e /snap/bin/slack ]] then
    sudo snap install --classic slack
fi
