#!/bin/zsh
set -eux -o pipefail

# config files
ln -sfT ~/config/dots/tmux.conf ~/.tmux.conf

( # prepare pipenv for tmux status line python code
    cd ~/config/dots/tmux.conf.d/bin
    sudo apt-get -qq install -y python3.7-dev # psutil needs python3.7-dev
    pipenv install
)

( # tmux from git

    sudo apt-get -yqq install git autoconf automake pkg-config libevent1-dev libncurses5-dev byacc

    [[ -e ~/tmux ]] || git clone https://github.com/tmux/tmux.git ~/tmux

    if [[ ! -e /usr/local/bin/tmux ]]; then
        cd ~/tmux
        sh autogen.sh
        ./configure
        make -j$(nproc)
        sudo make install
    fi

)


