#!/bin/zsh
set -eux -o pipefail

# config files
ln -sfT ~/config/dots/vim/vimrc ~/.vimrc
mkdir -p ~/.vim
ln -sfT ~/config/dots/vim/syntax ~/.vim/syntax
ln -sfT ~/config/dots/vim/ftdetect ~/.vim/ftdetect

# dependencies for vim plugins
pip3 install black

( # vim from git

    sudo apt-get -yqq install git libncurses5-dev

    [[ -e ~/vim ]] || git clone https://github.com/vim/vim.git ~/vim

    if [[ ! -e /usr/local/bin/vim ]]; then
        cd ~/vim
        sudo apt-get -yqq install libncurses5-dev
        ./configure \
            --disable-gui \
            --without-x \
            --enable-luainterp=dynamic \
            --enable-perlinterp=dynamic \
            --enable-pythoninterp=dynamic \
            --enable-rubyinterp \
            --enable-cscope \
            --with-features=huge
        make -j$(nproc)
        sudo make install
    fi

)

# todo I think plugged now installs plugins automatically the first time, no :PlugInstall needed here
