#!/bin/zsh
set -eux -o pipefail

sudo apt-get install -yqq python3 python3-pip build-essential python3-venv

mkdir -p ~/.config/pip
ln -sfT ~/config/i/python/pip.conf ~/.config/pip/pip.conf

pip3 install --upgrade pip

pip3 install ipython
mkdir -p ~/.ipython/profile_default
ln -sfT ~/config/i/python/ipython_config.py ~/.ipython/profile_default/ipython_config.py
echo 'we link our own ipython_config.py and wont know if the template changes with new options'
