#!/bin/zsh
set -eux -o pipefail

# NOTE should work for any 3.x version
python=python3.9

# https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa
sudo add-apt-repository -yu ppa:deadsnakes/ppa
# NOTE python3-pip allows to bootstrap pip into the actual python version package site later
sudo apt-get install -yq $python $python-venv $python-dev $python-distutils $python-tk python3-pip build-essential

# TODO this is actually empty now, recheck what are the settings, if nothing, remove
mkdir -p ~/.config/pip
ln -sfT ~/config/i/python/pip.conf ~/.config/pip/pip.conf

$python -m pip install --upgrade pip virtualenv ipython

# ipython
# TODO also see how to make it autoreload stuff, especially in debug mode
# TODO eventually see how to do cell/vim/notebook stuff?
mkdir -p ~/.ipython/profile_default
# see template.py, compare to new version every now and then
ln -sfT ~/config/i/python/ipython_config.py ~/.ipython/profile_default/ipython_config.py
