#!/bin/zsh
set -eux -o pipefail

sudo apt-get install -yq python3.9 python3.9-dev build-essential

mkdir -p ~/.config/pip
ln -sfT ~/config/i/python/pip.conf ~/.config/pip/pip.conf

# NOTE
# even though there can be multiple more pythons installed
# after the below, virtualenv and ipython commands point at this python version install
# I'm not sure, but I think whatever python version pip did it last determines what's available globally
python3.9 -m pip install --upgrade pip virtualenv ipython

# ipython
# TODO also see how to make it autoreload stuff, especially in debug mode
# TODO eventually see how to do cell/vim/notebook stuff?
mkdir -p ~/.ipython/profile_default
# see template.py, compare to new version every now and then
ln -sfT ~/config/i/python/ipython_config.py ~/.ipython/profile_default/ipython_config.py
