#!/bin/zsh
set -eux -o pipefail

# commandline helper (aliased to dbox)
if [[ ! -e ~/bin/dropbox.py ]]; then
    mkdir -p ~/bin
    wget 'https://www.dropbox.com/download?dl=packages/dropbox.py' -O ~/bin/dropbox.py
    chmod +x ~/bin/dropbox.py
else
    echo 'note: we dont redownload dropbox.py, not sure if that would ever be out of date'
fi

if [[ ! -e ~/.dropbox-dist ]]; then
    (
        cd ~
        # todo a bit shaky, could extract anything
        wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
        # it seems like the ~/.dropbox-dist will get updates itself
    )
fi

# install in systemd
# todo security risk to link files here?
sudo ln -sfT \
    ~/config/i/dropbox/dropbox@.service \
    /etc/systemd/system/dropbox@.service
sudo systemctl enable dropbox@$USER
sudo systemctl start dropbox@$USER

echo 'check dropbox status below, probably need to authenticate in a browser'
journalctl --follow --unit=dropbox@$USER.service || true

ln -sfT ~/Dropbox ~/dbox
ln -sfT ~/Dropbox/toys ~/toys

if [[ realpath ~/.osh/data != ~/Dropbox/osh-data ]]; then
    echo 'Maybe ~/.osh/data should point at ~/Dropbox/osh-data.'
    # NOTE not sure if I should do it scripted, it might not be synced yet here anyway
fi
