#!/bin/zsh
set -eux -o pipefail

# see
# https://wiki.debian.org/Keyboard
# https://help.ubuntu.com/community/Custom%20keyboard%20layout%20definitions?action=show&redirect=Howto%3A+Custom+keyboard+layout+definitions
# https://medium.com/@damko/a-simple-humble-but-comprehensive-guide-to-xkb-for-linux-6f1ad5e13450

sudo apt-get install -yq keyboard-configuration console-setup

sudo ln -sfT ~/config/i/keyboard/pointluck /usr/share/X11/xkb/symbols/pointluck

config=~/config/i/keyboard/config-$(hostname)
if [[ ! -f $config ]]; then
    echo "warning: using default keyboard config, no config for host $(hostname) found" >&2
    config=~/config/i/keyboard/config
fi
# configures it already for VT
sudo ln -sfT $config /etc/default/keyboard

# NOTE only needed for apple keyboard
echo options hid_apple fnmode=2 | sudo tee -a /etc/modprobe.d/hid_apple.conf
# TODO maybe not needed? makes it slow, but needs testing
sudo update-initramfs -u -k all
echo 'note: maybe reboot for apple F-keys to work like normal F-keys'

# TODO maybe one of those applies changes without restart?
sudo systemctl restart keyboard-setup.service
sudo udevadm trigger --subsystem-match=input --action=change

if [[ -v DISPLAY ]]; then
    # NOTE this probably works without restart
    # TODO taking the hostname is not always correct, in theory we should do what the config files says ... see above
    setxkbmap -layout pointluck -variant $(hostname) -verbose 10
    # NOTE we apply the xmodmap afterwards
    # the output of above setxkbmap shows that "symbols:    pc+pointluck(base)+inet(evdev)"
    # and inet(evdev) changes the high F13+ keys to be some multimedia stuff
    # so we change it aftewards. alternative might be to change the xkb rules, but seems complicated.
    # its okay because we dont need them in the VT, but only once in X, so we have it in xsession as well
    xmodmap ~/config/i/keyboard/mods
fi
