#!/bin/zsh
set -eux -o pipefail

this=$0
continue_from=${1:-}

cd ${0:a:h}

setups=(
    chrome
    spotify
    dropbox
)

if [[ $continue_from != '' ]]; then
    at=$setups[(i)$continue_from]
    if [[ $at -gt $#setups ]]; then
        echo "Cannot find $continue_from to continue from." 1>&2
        exit 1
    fi
    setups=$setups[$at,-1]
fi

function TRAPZERR {
    echo 'Setup failed for "'$i'". Fix and then resume with "'$this $i'".'
}
set +x
for i in $setups; do
    ../$i/setup
done
set -x
unset -f TRAPZERR

cat <<- EON
Some notes:
- maybe 'xrandr --output DP-0 --mode 3840x2160 --rate 120'
    - but that's not persistent, need nvidia-settings and
        - "X Server Display Configuration"
        - Advanced
        - select resolution non-auto and refresh rate
        - apply and save to configuration file
        - needed to make /usr/share/screen-resolution-extra/nvidia-polkit executable last time
- with ifi sound I used "AudioPro", ltstatus also has the alias for that one
- see notes/console and notes/grub for text mode resolutions and fonts
EON
