#!/bin/zsh
set -eux -o pipefail

# switch to HWE for ubuntu 20.04
# https://wiki.ubuntu.com/Kernel/LTSEnablementStack
#sudo apt-get update
#sudo apt-get upgrade -qqy
# todo hwe-20.04 not there (yet)
#sudo apt-get install -qqy --install-recommends xserver-xorg-hwe-20.04
echo 'note: xserver-xorg-hwe-20.04 might be ready now, did not exist on 2020-11-28'

sudo apt-get install -yqq xinit # for startx
# this installed a gretter already
sudo systemctl disable gdm.service
sudo systemctl stop gdm.service
sudo systemctl set-default multi-user.target

${0:a:h}/../nvidia/setup
echo 'nvidia-smi wont work before restart'

# apt installs (sorted)
i=()
i+=cool-retro-term
i+=d-feet  # introspect d-bus
i+=evince  # for the easier pdfs (when not using okular)
i+=feh # note also .xsession uses feh, is that the only way?
i+=firefox
i+=geeqie # pulls in many dependencies because of kde
i+=gnome-sushi # nautilus plugin for preview on space-key
i+=gpick # easy color picker from anything on the screen, useful when debugging terminal colors
i+=gthumb # together with scrot
i+=nautilus # filemanager gui
i+=scrot # screenshots
i+=transmission-gtk
i+=usbmount # ubuntu-desktop has something on its own, but this works coming from a server setup
i+=xclip
i+=xdotool # for xsession and spotify title
i+=yaru-theme-icon # gnome apps currently seem to use that one and dont depend on it when installing, might change again
#i+=kdenlive # seems ok for cutting videos
sudo apt-get install -qqy $i

# todo note above transmission gtk keep settings in
# /home/dkuettel/.config/transmission/settings.json
# add to config? not sure if all settings there are independent of machine
# also maybe dont install it by default? only at home?

# sorted list of snaps for desktop
#i=()
#i+=something
#sudo snap install $i

# ordered list of custom setups
setups=(
    redshift
    keyboard # probably not doing the right thing in virtual box
    dwm # sometimes '/dev/fb0: Permission denied' with startx, but probably not with good nvidia-drivers?
    dmenu
    alacritty # fonts might be missing here, ubuntu mono is probably always available
    sound
    chrome
    spotify
    dropbox
    okular
    syncthing
    slack
    vlc
)
for i in $setups; do
    ${0:a:h}/../$i/setup
done

# todo maybe some of the above need to be added as interactive? or just on demand? not all are fully unattended
