#!/bin/zsh
set -eux -o pipefail

# NOTE
# this could be both .xinitrc or .xsession
# startx calls .xinitrc and if it doesn't exist
# then it uses system defaults in /etc/X11/Xinit
# and /etc/X11/Xsession and then starts
# ~/.xsession which results in a cleaner setup
# (eg, dbus and other ubuntu(desktop) defaults)

# all log files here we recreate, we dont keep old xsession's logs
exec > >(ts '%F %T' >& .log-dwm)
exec 2>&1

# monitor off [idle seconds]
xset dpms 3600 3600 3600
# never run screensaver
xset s off
# switch off monitor in virtual terminal [idle minutes]
setterm --blank 20 --powerdown 20

redshift -r -v |& ts '%F %T' >& .log-redshift &

# NOTE we need this here because inet(evdev) is applied in xkb after our pointluck layout, see config/i/keyboard/setup
xmodmap ~/config/i/keyboard/mods

xset r rate 200 50  # keyboard repeat rate (delay ms, repeats per second)
numlockx on

xsetroot -bg black
xsetroot -solid black
feh --no-fehbg --bg-fill ~/config/i/dwm/5_stripes_landscape.jpg

# high dpi
export GDK_SCALE=2

function status {
    ~/config/i/ltstatus/ltstatus/examples/dwm-status.py
}

status >& .log-dwm-status &

dwm

kill %status || true
#kill %redshift || true  # seems to quit itself anyway, and this way there is no bright flash just before exiting
