#!/bin/zsh
set -eux -o pipefail

pip3 install --upgrade awscli

# see https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-other-package-management
# NOTE using version 1.19 for now because our aws kubernetes cluster is a bit older
sudo snap install kubectl --classic --channel=1.19/stable
sudo snap refresh kubectl
kubectl version --short --client

# we use the default profile in ~/.aws/config and ~/.aws/credentials
# NOTE we assume there is a default profile with a region
# otherwise add '--region eu-west-1' or something
aws eks update-kubeconfig --name deeplearning
kubectl get services
