#!/bin/zsh
set -eux -o pipefail

# currently not in any repository, installing from git
# NOTE snap has a version that is _not_ from the author
# from https://github.com/alacritty/alacritty
# install instructions might change (eg, dependencies change sometimes)

base=${0:a:h}
cd $base/alacritty

# this sets stable only for the current direction and subdirectories, not globally
rustup override set stable
rustup update stable

dependencies=(
    cmake
    pkg-config
    libfreetype6-dev
    libfontconfig1-dev
    libxcb-xfixes0-dev
    libxkbcommon-dev
    python3
    libegl1-mesa-dev  # only needed for wayland with nvidia gpu for EGL drivers
)
sudo apt-get install -y $dependencies

cargo build --release
infocmp alacritty || (echo 'no alacritty terminfo'; exit 1)
cp --force target/release/alacritty ~/bin
