#!/bin/zsh
set -eux -o pipefail

# currently not in any repository, installing from git
# NOTE snap has a version that is _not_ from the author
# from https://github.com/alacritty/alacritty
# install instructions might change (eg, dependencies change sometimes)

base=${0:a:h}
cd $base/alacritty

# this sets stable only for the current direction and subdirectories, not globally
rustup override set stable
rustup update stable

dependencies=(
    cmake
    pkg-config
    libfreetype6-dev
    libfontconfig1-dev
    libxcb-xfixes0-dev
    libxkbcommon-dev
    python3
    libegl1-mesa-dev  # only needed for wayland with nvidia gpu for EGL drivers
)
sudo apt-get install -y $dependencies

cargo build --release
# TODO it's also not clear if that is the up-to-date terminfo, is it copied as part of cargo build?
# also I think dependencies have changed with a new version, had a note somewhere? I think release
# page of alacritty mentions it
# indeed, see https://github.com/alacritty/alacritty/blob/master/INSTALL.md#post-build
# doing same in dbox/macos/alacritty/setup, when at it, make that macos stuff a git for versioning
infocmp alacritty || (echo 'no alacritty terminfo'; exit 1)
cp --force target/release/alacritty ~/bin
