#!/bin/zsh
set -eux -o pipefail

base=${0:a:h}
cd $base

(
    # use nerdfonts
    # see https://www.nerdfonts.com/font-downloads
    mkdir -p ~/.fonts
    cd ~/.fonts
    if [[ $(ls 'Ubuntu Mono'*'Nerd Font'* | wc -l) != 16 ]]; then
        wget -O nerd-font.zip https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/UbuntuMono.zip
        unzip nerd-font.zip
        rm nerd-font.zip
        fc-cache
    fi
)

(
    # currently not in any repository, installing from git
    # NOTE snap has a version that is _not_ from the author
    # from https://github.com/alacritty/alacritty
    # install instructions might change (eg, dependencies change sometimes)

    cd $base/alacritty

    if which rustup; then
        # TODO we might never update rustup?
        # see https://rust-lang.github.io/rustup/basics.html#keeping-rustup-up-to-date ?
    else
        curl --fail --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o ./install-rustup.sh
        # NOTE paths are set already in i/zsh/path.zsh for rustup
        sh install-rustup.sh -y --no-modify-path
        rm install-rustup.sh
    fi
    rustup override set stable
    rustup update stable

    dependencies=(
        cmake
        pkg-config
        libfreetype6-dev
        libfontconfig1-dev
        libxcb-xfixes0-dev
        libxkbcommon-dev
        python3
        libegl1-mesa-dev  # only needed for wayland with nvidia gpu for EGL drivers
    )
    sudo apt-get install -y $dependencies

    cargo build --release
    infocmp alacritty || (echo 'no alacritty terminfo'; exit 1)
    cp --force target/release/alacritty ~/bin
)

# TODO could also install zsh completion for alacritty
# see https://github.com/alacritty/alacritty/blob/master/INSTALL.md#zsh

# TODO the config file is copied from the template in ./alacritty/alacritty.yaml
# sometimes check the diff to see if new features are there
ln -sfT $base/alacritty.yml ~/.alacritty.yml
