#!/bin/zsh
set -eux -o pipefail

base=${0:a:h}
cd $base

(
    # use nerdfonts
    # see https://www.nerdfonts.com/font-downloads
    mkdir -p ~/.fonts
    cd ~/.fonts
    if [[ $(ls 'Ubuntu Mono'*'Nerd Font'* | wc -l) != 16 ]]; then
        wget -O nerd-font.zip https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/UbuntuMono.zip
        unzip nerd-font.zip
        rm nerd-font.zip
        fc-cache
    fi
)

(
    # currently not in any repository, installing from git
    # NOTE snap has a version that is _not_ from the author
    # from https://github.com/alacritty/alacritty
    # install instructions might change (eg, dependencies change sometimes)

    cd $base/alacritty

    # this sets stable only for the current direction and subdirectories, not globally
    rustup override set stable
    rustup update stable

    dependencies=(
        cmake
        pkg-config
        libfreetype6-dev
        libfontconfig1-dev
        libxcb-xfixes0-dev
        libxkbcommon-dev
        python3
        libegl1-mesa-dev  # only needed for wayland with nvidia gpu for EGL drivers
    )
    sudo apt-get install -y $dependencies

    cargo build --release
    infocmp alacritty || (echo 'no alacritty terminfo'; exit 1)
    cp --force target/release/alacritty ~/bin
)

# TODO could also install zsh completion for alacritty
# see https://github.com/alacritty/alacritty/blob/master/INSTALL.md#zsh

# TODO the config file is copied from the template in ./alacritty/alacritty.yaml
# sometimes check the diff to see if new features are there
ln -sfT $base/alacritty.yml ~/.alacritty.yml
