#!/bin/zsh
set -eux -o pipefail

h=${0:a:h}

# dependencies for some plugins
pip3 install black pynvim isort black

( # treesitter
    cd $h/config/pack/plugins/opt/nvim-treesitter
    nvim -Es <<- 'EOF'
        TSUpdateSync
        TSInstallSync all
        qa
    EOF
)

( # telescope & co
    cd $h/config/pack/plugins/opt/telescope.nvim
    sudo apt-get -y install fd-find ripgrep
    cd $h/config/pack/plugins/opt/telescope-fzf-native.nvim
    make
)

( # pyright for python lsp
    if ! which pyright-langserver; then
        npm install -g pyright
    fi
)

# regenerate helptags
nvim -Es <<- 'EOF'
    helptags ALL
    qa
EOF
