#!/bin/zsh
set -eux -o pipefail

h=${0:a:h}
cd $h

# main config ~/.config/nvim is completely in git
# nvim keeps that folder clean
mkdir -p ~/.config
ln -sfT $h/config ~/.config/nvim

./install
./plugins
