#!/bin/zsh
set -eux -o pipefail

h=${0:a:h}
cd $h

# main config ~/.config/nvim is completely in git, nvim keeps that folder clean
mkdir -p ~/.config
ln -sfT $h/config ~/.config/nvim

(
    # there is also ~/.local/share/nvim which contains transient data
    # but there should not be too much, especially from an old installiation
    # since things are sourced by nvim
    mkdir -p ~/.local/share/nvim
    cd ~/.local/share/nvim
    accept=(rplugin.vim shada swap telescope_history)
    for i in $(ls); do
        (( ${accept[(i)$i]} <= ${#accept} ))
    done
)

./install
./plugins

