#!/bin/zsh
set -eux -o pipefail

h=${0:a:h}

# config files
ln -sfT $h/config/vimrc ~/.vimrc
mkdir -p ~/.vim
ln -sfT $h/config/syntax ~/.vim/syntax
ln -sfT $h/config/ftdetect ~/.vim/ftdetect

# dependencies for vim plugins
pip3 install black

( # vim from git
    cd $h/vim

    sudo apt-get install -yqq git libncurses5-dev

    ./configure \
        --disable-gui \
        --without-x \
        --enable-luainterp=dynamic \
        --enable-perlinterp=dynamic \
        --enable-pythoninterp=dynamic \
        --enable-rubyinterp \
        --enable-cscope \
        --with-features=huge
    make -j$(nproc)
    sudo make install
)

if [[ ! -f ~/.vim/autoload/plug.vim ]]; then
    curl --fail --location --create-dirs \
         --output ~/.vim/autoload/plug.vim \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    vim -c PlugInstall
    # todo but how to make it exit after done, if no error?
fi
