#!/bin/zsh
set -eux -o pipefail

h=${0:a:h}

# config files
mkdir -p ~/.config/nvim
ln -sfT $h/config/vimrc ~/.config/nvim/init.vim
ln -sfT $h/config/syntax ~/.config/nvim/syntax
ln -sfT $h/config/ftdetect ~/.config/nvim/ftdetect

# dependencies for vim plugins
pip3 install black pynvim

( # nvim from git
    cd $h/nvim

    sudo apt-get install -yqq ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip

    # maybe to start fresh: make distclean
    make CMAKE_BUILD_TYPE=Release
    # todo any list of features like in vim?
    sudo make install
)


if [[ ! -f ~/.local/share/nvim/site/autoload/plug.vim ]]; then
    curl --fail --location --create-dirs \
        --output ~/.local/share/nvim/site/autoload/plug.vim \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    nvim -c PlugInstall
    # todo but how to make it exit after done, if no error?
fi
