#!/bin/zsh
set -eux -o pipefail

sudo apt-get update
sudo apt-get -q upgrade -y

# switch to HWE for ubuntu 18.04
# https://wiki.ubuntu.com/Kernel/LTSEnablementStack
sudo apt-get -q install -y --install-recommends linux-generic-hwe-18.04
# note:
# after this autoremove can remove some old packages
# for desktop systems we also want xserver-xorg-hwe-18.04 (see ./plus-head)

# a generic list of useful packages
# many are also installed and configured by more specific scripts
i=()
i+=bmon # bandwidth monitor
i+=cmake
i+=dtrx # easy and clean archive extraction
i+=feh
i+=g++
i+=gcp # like cp, but with progress bar among other features
i+=geeqie
i+=git
i+=htop
i+=jq # json query engine
i+=libboost-dev
i+=lnav # log file viewer
i+=markdown # for my ptc notes standup.markdown
i+=moreutils # sponge
i+=mosh # ssh robust for unstable connections
i+=openssh-server
i+=pv # monitor data progress thru a pipe
i+=sshfs
i+=suckless-tools
i+=sysstat
i+=tmux
i+=tree
i+=unzip
i+=vim
i+=xclip
i+=zip
i+=zsh

sudo apt-get -q install -y $i
