#!/bin/zsh
set -eux -o pipefail

# switch to HWE for ubuntu 20.04
# https://wiki.ubuntu.com/Kernel/LTSEnablementStack
#sudo apt-get update
#sudo apt-get upgrade -qqy
# todo hwe-20.04 not there (yet)
#sudo apt-get install -qqy --install-recommends xserver-xorg-hwe-20.04
echo 'note: xserver-xorg-hwe-20.04 might be ready now'

sudo apt-get install xinit # for startx
# this installed a gretter already
sudo systemctl disable gdm.service

i/nvidia
echo 'nvidia-smi wont work before restart'

# apt installs (sorted)
i=()
i+=feh # note also .xsession uses feh, is that the only way?
i+=firefox
i+=geeqie # pulls in many dependencies because of kde
i+=gthumb # together with scrot
i+=scrot # screenshots
i+=transmission-gtk
i+=xclip
sudo apt-get install -qqy $i

# todo note above transmission gtk keep settings in
# /home/dkuettel/.config/transmission/settings.json
# add to config? not sure if all settings there are independent of machine
# also maybe dont install it by default? only at home?

# sorted list of snaps for desktop
i=()
i+=vlc
sudo snap install $i

# ordered list of custom setups
setups=(
    redshift
    keyboard # probably not doing the right thing in virtual box
    dwm # sometimes '/dev/fb0: Permission denied' with startx, but probably not with good nvidia-drivers?
    st # fonts are missing here, because on dropbox, default ubuntu and be done, or add to git?
    sound
    chrome
    spotify
    dropbox
    okular
    syncthing
)
for i in $setups; do
    ${0:a:h}/../i/$i/setup
done

exit 1

i/slack

# todo maybe anyway have it as an "interactive" list? not all can be really unattended
