#!/bin/zsh
set -eux -o pipefail

# this installs the command line version only
# it seems like the ~/.dropbox-dist will get updates itself
# but not the bin/dropbox.py that we download manually
# note:
#   first time you install/start it you have to login, check systemctl status dropbox@dkuettel for login link
#   use dbox (~/config/bin) for easy command line access


if [[ ! -d ~/.dropbox-dist ]]; then
    cd ~
    wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
fi

# copy the command line helper to ~/bin
# not to the ~/.dropbox-dist folder,
# because that one gets wiped on updates
mkdir -p ~/bin
wget 'https://www.dropbox.com/download?dl=packages/dropbox.py' -O ~/bin/dropbox.py
chmod +x ~/bin/dropbox.py

# install in systemd
if [[ $(realpath /etc/systemd/system/dropbox@.service) != $(realpath ~/config/dots/dropbox.d/dropbox@.service) ]]; then
    # todo security risk to link files?
    sudo ln -sfT --backup=numbered \
        ~/config/dots/dropbox.d/dropbox@.service \
        /etc/systemd/system/dropbox@.service
fi
systemctl enable dropbox@$USER
systemctl start dropbox@$USER
sleep 5
systemctl status dropbox@$USER
