#!/bin/zsh
set -eux -o pipefail

if [[ ! -d ~/dwm ]]; then
	git clone git@bitbucket.org:dkuettel/dwm.git ~/dwm
	cd ~/dwm
	./setup-requirements.sh
	./setup-git.sh
	./install.sh
fi

t=~/config/dots/dwm; l=~/.xinitrc
if [[ ! ( $t -ef $l ) ]]; then
	ln -sfT --backup=numbered $t $l
fi

( # cursor themes for X
	sudo apt-get -yqq install oxygen-cursor-theme oxygen-cursor-theme-extra
	mkdir -p ~/.icons
	ln -sfT /usr/share/icons/oxy-blue/ ~/.icons/default
)

if [[ ! -d ~/dmenu ]]; then
	git clone git@bitbucket.org:dkuettel/dmenu.git ~/dmenu
	cd ~/dmenu
	./setup-git.sh
	./install.sh
fi

# slock
if [[ ! -d ~/slock ]]; then
	git clone https//git.suckless.org/slock ~/slock
	cd ~/slock
	sudo apt-get -yqq install libx11-dev make gcc libxft-dev libxinerama-dev libxrandr-dev
	make clean
	make
	sudo make install
fi

# st
if [[ ! -d ~/st ]]; then
	git clone git@bitbucket.org:dkuettel/st.git ~/st
	cd ~/st
	./setup-requirements.sh
	./setup-git.sh
	./install.sh
fi
