#!/bin/zsh
set -eux -o pipefail

sudo apt-get -q -install -y python3 python3-pip build-essential
pip3 install --upgrade

sudo apt-get -q install -y ipython3
if [[ $(realpath ~/.ipython/profile_default/ipython_config.py) != $(realpath ~/config/dots/python/ipython_config.py) ]]; then
    mkdir -p ~/.ipython/profile_default
    ln -sfT ~/config/dots/python/ipython_config.py ~/.ipython/profile_default/ipython_config.py
fi
