#!/bin/zsh
set -eux -o pipefail

sudo apt-get -q install -y python3 python3-pip build-essential

mkdir -p ~/.config/pip
if [[ $(realpath ~/.config/pip/pip.conf) != $(realpath ~/config/dots/pip/pip.conf) ]]; then
    ln -sfT --backup=numbered ~/config/dots/pip/pip.conf ~/.config/pip/pip.conf
fi

pip3 install --upgrade pip

pip3 install ipython
mkdir -p ~/.ipython/profile_default
if [[ $(realpath ~/.ipython/profile_default/ipython_config.py) != $(realpath ~/config/dots/python/ipython_config.py) ]]; then
    # we use our own config which was originally created by changing ipythons config template
    # if ever this is changed or extended, we won't know about it
    ln -sfT --backup=numbered ~/config/dots/python/ipython_config.py ~/.ipython/profile_default/ipython_config.py
fi
