#!/bin/bash
set -eux -o pipefail

# switch to zsh
if [ -z ${ZSH_VERSION+1} ]; then
    which zsh || i/zsh
    exec zsh $0
fi

# pip3 needs this, after setup it's in the zsh config
export PATH=$HOME/.local/bin:$PATH

# switch to HWE for ubuntu 18.04
# https://wiki.ubuntu.com/Kernel/LTSEnablementStack
sudo apt-get update
sudo apt-get upgrade -qqy
# todo install and autoremove have some interactive popups that ask keep local or update (local seems ok)
# (at least on ec2 ubuntu that happens), could make more unattended?
sudo apt-get install -qqy --install-recommends linux-generic-hwe-18.04
sudo apt-get autoremove -y

# sorted list of packages for server (not desktop)
i=()
i+=bmon # bandwidth monitor
i+=cmake
i+=dkms
i+=dtrx # easy and clean archive extraction
i+=g++
i+=gcp # like cp, but with progress bar among other features
i+=git
i+=htop
i+=jq # json query engine
i+=libboost-dev
i+=lnav # log file viewer
i+=markdown # for my ptc notes standup.markdown
i+=moreutils # sponge
i+=mosh # ssh robust for unstable connections
i+=openssh-server
i+=pv # monitor data progress thru a pipe
i+=sshfs
i+=suckless-tools
i+=sysstat
i+=tree
i+=unzip
i+=vim
i+=zip
i+=zsh
sudo apt-get install -qqy $i

# customized tools
i/ssh
i/git
i/fzf
i/top
i/htop
i/python
${0:a:h}/../i/pdocs/setup
${0:a:h}/../i/tmux/setup
${0:a:h}/../i/vim/setup

# todo if you want to ssh to this machine using st
# you need to update /etc/terminfo with the st entries
# best as they come from compiling it yourself (ubuntu default st entries have a typo, tmux+nvim will fail)
# but another option would be to add it here? or when st is a submodule have a commit with them prepared?
# then copy in the right place
echo 'see above for st logins'
exit 1
