#!/bin/bash
set -eux -o pipefail
# switch to zsh
if [ -z "$ZSH_VERSION" ]; then
    which zsh || i/zsh
    exec zsh $0
fi

# todo still needed now that we try to restart with zsh?
# pip3 needs this and here we are still in the old shell
#export PATH=$HOME/.local/bin:$PATH
echo 'check path, still needed?'
echo $PATH
exit 1

# switch to HWE for ubuntu 18.04
# https://wiki.ubuntu.com/Kernel/LTSEnablementStack
sudo apt-get update
sudo apt-get upgrade -qqy
# todo install and autoremove have some interactive popups that ask keep local or update (local seems ok)
# (at least on ec2 ubuntu that happens), could make more unattended?
sudo apt-get install -qqy --install-recommends linux-generic-hwe-18.04
sudo apt-get autoremove -y

# sorted list of packages for server (not desktop)
i=()
i+=bmon # bandwidth monitor
i+=cmake
i+=dkms
i+=dtrx # easy and clean archive extraction
i+=g++
i+=gcp # like cp, but with progress bar among other features
i+=git
i+=htop
i+=jq # json query engine
i+=libboost-dev
i+=lnav # log file viewer
i+=markdown # for my ptc notes standup.markdown
i+=moreutils # sponge
i+=mosh # ssh robust for unstable connections
i+=openssh-server
i+=pv # monitor data progress thru a pipe
i+=sshfs
i+=suckless-tools
i+=sysstat
i+=tmux
i+=tree
i+=unzip
i+=vim
i+=zip
i+=zsh
sudo apt-get install -qqy $i

# customized tools
i/ssh
i/git
i/fzf
i/top
i/htop
i/python
i/tmux
i/vim
i/nvim
