#!/bin/zsh
set -eux -o pipefail

if which spotify; then
else
	sudo snap install spotify
	# non-snap installation
	#sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BBEBDCB318AD50EC6865090613B00F1FD2C19886
	#echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
	#sudo apt-get update
	#sudo apt-get -yqq install spotify-client
	# todo not sure if that will work, the spotify folder and prefs only get created when it's started the first time
	# todo unfortunately this doesnt seem to work
	#mkdir -p ~/.config/spotify/Users/dkuettel-user
	#cp spotify/prefs ~/.config/spotify/Users/dkuettel-user
fi

mkdir -p ~/plugins

( 
	# playerctl
	cd ~/plugins
	if [[ ! -d playerctl ]]; then
		git clone https://github.com/acrisci/playerctl.git
	fi
	cd playerctl
	git pull
	sudo apt-get -yqq install gtk-doc-tools gobject-introspection libglib2.0-dev autoconf libtool
	./autogen.sh
	make
)
