#!/bin/zsh
set -eux -o pipefail

# https://docs.syncthing.net/intro/getting-started.html
sudo apt install syncthing

# https://docs.syncthing.net/users/autostart.html#linux
systemctl enable syncthing@$USER.service
systemctl start syncthing@$USER.service

# check with
systemctl status syncthing@$USER.service
