#!/bin/zsh
set -eux -o pipefail

# note: ubuntu 16.04 has an older tmux version 2.1
# note: ubuntu 18.04 has tmux version 2.6

sudo apt-get -qq install -y tmux \
    sysstat # mpstat in tmux status, todo might remove if we do all in python

( # prepare pipenv for tmux status line python code
    cd ~/config/dots/tmux.conf.d/bin
    sudo apt install python3.7-dev # psutil needs python3.7-dev
    pipenv install
)

# todo use newest tmux? make sure it's in the path and shadowing apt installed one
# build latest version of tmux
#sudo apt-get -yq install automake libevent1-dev libncurses5-dev
#if [[ ! -d ~/tmux ]]; then
#   sudo apt-get install -yq automake libevent-dev
#   git clone https://github.com/tmux/tmux.git ~/tmux
#   cd ~/tmux
#   sh autogen.sh
#   ./configure
#   make -j$(nproc)
#else
#   cd ~/tmux
#   git pull
#   make
#fi

if [[ $(realpath ~/.tmux.conf) != $(realpath ~/config/dots/tmux.conf) ]]; then
    ln -sfT --backup=numbered ~/config/dots/tmux.conf ~/.tmux.conf
fi
