#!/bin/zsh
set -eux -o pipefail

sudo apt-get -yqq install vim

if [[ $(realpath ~/.vimrc) != $(realpath ~/config/dots/vimrc) ]]; then
    ln -sfT --backup=numbered ~/config/dots/vimrc ~/.vimrc
fi

## vundle
#if [[ -d ~/.vim/bundle/Vundle.vim ]]; then
    #git -C ~/.vim/bundle/Vundle.vim pull
#else
    #git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
#fi
#vim -u ~/config/dots/vimrc.d/vundle.vim +PluginInstall +qall
#vim -u ~/config/dots/vimrc.d/vundle.vim +PluginUpdate +qall

# link custom files
#if [[ ! -d ~/.vim ]]; then
#	mkdir ~/.vim
#fi
#ln -sfT ~/config/vim/syntax ~/.vim/syntax
#ln -sfT ~/config/vim/ftdetect ~/.vim/ftdetect
#ln -sfT ~/config/vim/after ~/.vim/after
