#!/bin/zsh
set -eux -o pipefail

base=${0:a:h}

ln -sfT $base ~/.pdocs

(
    cd $base

    if [[ ! -d .venv ]]; then
        vv-init
    fi

    vv pip-sync

    PYTHONPATH=$base/pdocs vv python build_index.py
)
