#!/bin/zsh
set -eux -o pipefail

base=${0:a:h}

ln -sfT $base ~/.pdocs

# something in my usual env needs tkinter
# seems cannot be installed with pipenv
sudo apt-get -yqq install python3-tk

(
    cd $base

    if [[ ! -d .venv ]]; then
        vv-init
    fi

    vv pip-sync

    vv python build_index.py
)
