#!/bin/zsh
set -eux -o pipefail

# ubuntu 20.04 has a recent version of docker
# TODO this started and interactive prompt if /etd/docker/daemon.json was already edited
# (like by nn repo setup), and it doesnt automatically take the default but fail because we have it interactive
sudo apt-get -yqq install --no-install-recommends docker.io

# test
sudo docker run hello-world

# to use it without sudo
sudo usermod -aG docker $USER
echo 'use of docker without sudo only takes effect after new login, ssh localhost, su --login $USER, new tmux server, ...'

if which nvidia-smi >/dev/null; then

    curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | \
        sudo tee /etc/apt/trusted.gpg.d/nvidia-docker.gpg
    curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu$(lsb_release --release --short)/nvidia-docker.list | \
        sudo tee /etc/apt/sources.list.d/nvidia-docker.list

    sudo apt-get update
    sudo apt-get -yqq install nvidia-docker2

    # reload the settings
    sudo service docker restart

    # could also pull latest potentially
    # TODO docker run --gpus all also works now, profile is needed, but nvidia-docker probably not anymore
    sudo nvidia-docker run --rm nvidia/cuda:9.0-cudnn7-runtime nvidia-smi

fi
