#!/bin/zsh
set -eux -o pipefail

cd ~/.osh
target=~/sbox/osh-data

# check for a clean state
[[ -d $target ]]
[[ $(ls archive | wc -l) == 0 ]]
[[ $(ls active | wc -l) == 1 ]]
[[ -f active/$(hostname).osh ]]
[[ ! -f $target/active/$(hostname).osh ]]

# move
rmdir archive
ln -sfT $target/archive archive
mv active/$(hostname).osh $target/active
rmdir active
ln -sfT $target/active active
rm event-filters.yaml
ln -sfT $target/event-filters.yaml event-filters.yaml

systemctl --user restart osh.service
